  name: Tests CI/CD

  on: ["push"]

  env:
    DATABASE_NAME: "test"

  jobs:
    dummy-job:
      strategy:
        matrix:
          version: [ 14 , 16 , 18 ]
      name: "my job"
      runs-on:  ubuntu-latest
      steps:
        - run: ls -la
        # on récupère le contenu du dépôt
        - uses: actions/checkout@v3
        - run: ls -la
        - name: "Installation de node ${{ matrix.version }}x"
          uses: actions/setup-node@v3
          with:
            # on dit d'installer la version 
            node-version: ${{ matrix.version }}
        - run: node -v
        # ${{ ... }} utilise une variable pour le contexte
        - run: echo ${{ github.actor }}  ${{ github.event_name }}
        - run: printenv
        # Les variables d'env sont passées au script (normalement)
        - run: node dummy.js
          env: 
            DATABASE_NAME: 'override du database name'