name: Tests CI/CD

on: ["push"]

jobs:
  dummy-job:
    name: "my job"
    runs-on:  ubuntu-latest
    steps:
      - run: ls -la
      # on récupère le contenu du dépôt
      - uses: actions/checkout@v3
      - run: ls -la
      - name: "Installation de node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: node -v
      - run: echo ${{github.actor}}