name: Tests CI/CD

on: ["push"]

jobs:
  dummy-job:
    name: "my job"
    runs-on:  ubuntu-latest
    steps:
      - run: ls -lah
      - uses: actions/checkout@v3
      - run: ls -lah
      - name: "installation de node"
        uses: actions/setup-node@v-3
        with:
         node-version: 18
      - run: node-v 